#!/usr/bin/env bash
# Transfer a file to a server
# parameters:
#	$1 The path to the file to be transferred
#	$2 The IP of the server we want to transfer the file to
#	$3 The username scp connects with
#	$4 The path to the SSH private key that scp uses

# print message if argument count is less than 3
argcount=0
for _ in "$@"; do
	argcount=$((argcount+1))
done
if [ "$argcount" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

# format "scp -i key_path source_path username@ip:destination_path"
# 	 "scp -i    $4 		$1		$3@$2:~/
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
