#!/usr/bin/env bash
# Transfer a file to a server

# print message if argument count is less than 3
argcount=0
for _ in "$@"; do
	argcount=$((argcount+1))
done
if [ "$argcount" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
echo "$argcount"

# turning off strict host key checking
if [ -f ~/.ssh/config ]; then
	echo "StrictHostKeyChecking no" >> ~/.ssh/config
else
	echo "StrictHostKeyChecking no" > ~/.ssh/config
fi
# format "scp -i key_path source_path username@ip:destination_path"
# 	 "scp -i    $4 		$1		$3@$2:~/
echo "scp $4 $1 $3@$2:~/"
scp -i "$4" "$1" "$3@$2:~/"
