#!/usr/bin/env bash
# Configure a new Ubuntu machine with Nginx installation
# requirements:
# 	install it on my web server
#	it should listen on port 80
#	GET at its root should return a page with(Hello World!) text
# !!no use of systemctl!! :(

# install nginx(enginex)
sudo apt-get -y update
sudo apt -y install nginx

# configure firewall to allow normal unencrypted traffic
# this opens only port 80
sudo ufw allow 'Nginx HTTP'
# return a page that contains the string Hello World! when querying at root
# by modifying the default nginx landing page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# ++ Redirection- redirect /redirect_me page to sth else;)
other_place="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
line="rewrite ^/redirect_me/$ $other_place permanent;"
file="/etc/nginx/sites-available/default"
line_no=$(sed -n '/root \/var\/www\/html;/=' $file)

sed  "${line_no}a\\$line" /etc/nginx/sites-available/default > tmp
sudo mv tmp /etc/nginx/sites-available/default
sudo service nginx restart
