#!/usr/bin/env bash
# Configure a new Ubuntu machine with Nginx installation
# requirements:
# 	install it on my web server
#	it should listen on port 80
# Http response should contain custom header
# 	X-Served-By : hostname_of_server

# install nginx(enginex)
sudo apt-get -y update
sudo apt -y install nginx

# configure firewall to allow normal unencrypted traffic
# this opens only port 80
sudo ufw allow 'Nginx HTTP'

# find line number of "/root /var/www/html;" to add configuration data after
file="/etc/nginx/sites-available/default"
line_no=$(sed -n '/root \/var\/www\/html;/=' $file)

# create a copy to avoid permission issues then replace
line="add_header X-Served-By $HOSTNAME;"

sed "${line_no}a\\$line" /etc/nginx/sites-available/default > tmp
sudo mv tmp /etc/nginx/sites-available/default

sudo service nginx start
