#!/usr/bin/env bash
# Configure a new Ubuntu machine with Nginx installation
# requirements:
# 	install it on my web server
#	it should listen on port 80
# Http response should contain custom header
# 	X-Served-By : hostname_of_server



# create a new page
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# create a 404 page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# find line number of "/root /var/www/html;" to add configuration data after
#file="/etc/nginx/sites-available/default"i
file="testf"
tmpfile="tmpf"
line_no=$(sed -n '/root \/var\/www\/html;/=' $file)

# define configuration lines
echo "
add_header X-Served-By $HOSTNAME;
index index.html;
location /redirect_me {
	return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley;
}" > $tmpfile
cat "$tmpfile"
#echo $lines
#echo $line_no
# create a copy to avoid permission issues then replace
sed "${line_no}r $tmpfile" "$file" > tmpsed
sudo mv tmpsed "$file"
rm "$tmpfile"

