#!/usr/bin/env bash

# v1
# sudo systemctl reload gunicorn

# v2
# ps aux: Lists all running processes.
# grep gunicorn: Filters processes containing "gunicorn".
# awk '{ print $2 }': Extracts the second column (PID) from the ps output.
# xargs kill -HUP: Passes each PID to kill with the HUP signal for graceful reload.
PID=$(pgrep gunicorn)
kill -s HUP $((PID))

